### ISSUE TITLE
Why rosgraph_msgs/Log contains field `topic` ?

### ISSUE THREAD

**Issue by flplv** [ros/ros_comm_msgs#10]
If you use nodelets you will often load a lot of different applications within the same node, and the `topic` field for every rosout message can be huge. 

On our system, we are transferring through the wire 45KiB of extra payload per console message only because of the topic list.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now.

---

There seems to be a question asking for exactly what you are looking for: https://answers.ros.org/question/301590/how-to-always-load-a-parameter-without-adding-it-to-every-launch-file/
