### ISSUE TITLE
ImportError: cannot import name 'Log' from 'rosgraph_msgs.msg'

### ISSUE THREAD

**Issue by clebio** [ros/ros_comm_msgs#13]
On a new install of Foxy Fitzroy on Ubuntu Focal, I was trying to run `roslaunch gazebo_simulation_scene gazebo_simulation_scene.launch`. However, that fails with the titular error message. To simply this further, just trying to import `roslaunch` does the same:

```
$ python -c 'import roslaunch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/roslaunch/__init__.py", line 62, in <module>
    from .scriptapi import ROSLaunch
  File "/usr/lib/python3/dist-packages/roslaunch/scriptapi.py", line 42, in <module>
    import roslaunch.parent
  File "/usr/lib/python3/dist-packages/roslaunch/parent.py", line 54, in <module>
    import roslaunch.server
  File "/usr/lib/python3/dist-packages/roslaunch/server.py", line 79, in <module>
    from rosgraph_msgs.msg import Log
ImportError: cannot import name 'Log' from 'rosgraph_msgs.msg' (/opt/ros/foxy/lib/python3.8/site-packages/rosgraph_msgs/msg/__init__.py)
```

This is on a new ROS setup on Ubuntu:

```
$ printenv | grep ROS
ROS_VERSION=2
ROS_PYTHON_VERSION=3
ROS_LOCALHOST_ONLY=0
ROS_DISTRO=foxy

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ python -V
Python 3.8.5
```

**Comment by kmindspark** [comment]
Same issue here, is there a solution to this?

**Comment by colian** [comment]
Looking forward the answer too.

**Comment by Megaa-Hub** [comment]
Based on the error message, it looks like you've sourced a ROS 1 installation and a ROS 2 installation in the same shell. This is not recommended (except for a shell where you are running ros1_bridge).

Since rosservice is a ROS 1 command, you should not source any ROS 2 installation in the same shell, then the command should work as expected.

**Comment by EthanCodesss** [comment]
Same issue!!

**Comment by JesseSarria** [comment]
Similar issue here, but on eloquent.

**Comment by NazarK0** [comment]
similar issue, but on Galactic

**Comment by Udaykiran87** [comment]
did any one find answer? I am unable to play the rosbag file using ros1 bridge. When i am trying to filter out some topics then also i am not able filter out.

**Comment by baharaks** [comment]
Same problem with ROS Foxy.

**Comment by boyarzun** [comment]
Same issue with ROS Foxy.

**Comment by amplexus** [comment]
Same issue with ROS rolling.

**Comment by keli95566** [comment]
Same problem with ROS Foxy.

**Comment by hidmic** [comment]
Alright, to answer everyone before closing -- though I presume you've already found out. 

This repository only hosts the `rosgraph_msgs` package for ROS 1. The `rosgraph_msgs` package for ROS 2 lives in https://github.com/ros2/common_interfaces, but it doesn't hold the `Log` message anymore. It has been relocated to the [`rcl_interfaces` package](https://github.com/ros2/rcl_interfaces/blob/master/rcl_interfaces/msg/Log.msg).

**Comment by quanyan2343** [comment]
So, how to solve this issue.

**Comment by quanyan2343** [comment]
So, how to solve this issue.

**Comment by Oballon** [comment]
So, how to solve this issue?

**Comment by maxlu96** [comment]
roscore has been replaced in ros2, reed more here:

https://www.theconstructsim.com/ros2-in-5-mins-003-where-is-roscore-in-ros2/

**Comment by whwang8** [comment]
I don't think you can use ros2 with gazebo, at least it's not the recommended version.  If you look at the tutorial, it recommends ros noetic among others.  Thought I'd post because I was banging my head against a while with this.

http://gazebosim.org/tutorials?tut=ros_installing&cat=connect_ros

**Comment by whwang8** [comment]
> 

http://gazebosim.org/tutorials?tut=ros_wrapper_versions&cat=connect_ros

This shows which combinations of versions you can use!

**Comment by maxlu96** [comment]
> I don't think you can use ros2 with gazebo, at least it's not the recommended version. If you look at the tutorial, it recommends ros noetic among others. Thought I'd post because I was banging my head against a while with this.
> 
> http://gazebosim.org/tutorials?tut=ros_installing&cat=connect_ros

I used ros2 foxy with Gazebo and it workes fine

**Comment by t0stiman** [comment]
Solution: use `ros2 launch` instead of `roslaunch`.

**Comment by lisimmy** [comment]
$ printenv | grep ROS
ROS_VERSION=2

use ros2 xxx 
eg： ros2 topic list

Call `ros2 <command> -h` for more detailed usage.

**Comment by dieter-aerit** [comment]
`ros2 launch rosbridge_server rosbridge_websocket_launch.xml` solves it in my case.

**Comment by devrajshetake** [comment]
I am using `ros2 launch` still getting the same error.

**Comment by KevinKipkorir254** [comment]
Hello found the solution Use 
![Screenshot (21)](https://github.com/ros/ros_comm_msgs/assets/96063788/3876b07e-28cc-42f6-bcc5-e731290171b4)

**Comment by litouxinxin** [comment]
Confirm whether your file type is .lauch or .py, and then use the `ros2 lauch` command to run it. `ros2 launch carla_ros_bridge carla_ros_bridge.launch.py.`
