### ISSUE TITLE
Hydro-Indigo version conflict

### ISSUE THREAD

**Issue by stonier** [ros/ros_comm_msgs#3]
Hydro versions ([ros_comm](https://github.com/ros/ros_comm/tree/hydro-devel/messages)) > Indigo versions ([ros_comm_msgs](https://github.com/ros/ros_comm_msgs)). 

These are [1.10.12](http://www.ros.org/debbuild/hydro.html?q=rosgraph_msgs) vs [1.10.3](http://www.ros.org/debbuild/indigo.html?q=rosgraph_msgs) respectively.

This is causing a problem in the java maven repositories where it's not only writing over older versions, but pulling in older hydro versions when given an open ended version dependency (e.g. [1.10, 1.11)).

Might these indigo versions get a nudge?

**Comment by dirk-thomas** [comment]
Thanks, tagged (https://github.com/ros/ros_comm_msgs/tree/1.11.0) and released (https://github.com/ros/rosdistro/pull/7315).
