### ISSUE TITLE
trigger new indigo release containing std_srvs/Trigger

### ISSUE THREAD

**Issue by floweisshardt** [ros/ros_comm_msgs#6]
A new service `std_srvs/Trigger` was added in #5 which is still missing in the release version. This issue is to keep in mind to trigger a new indigo release (@dirk-thomas)

**Comment by dirk-thomas** [comment]
I am waiting for a decision on one ticket (ros/catkin#728) before releasing all core packages.

**Comment by dirk-thomas** [comment]
Finally in flight: ros/rosdistro#7964
